#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------

FLINK_VERSION_STABLE: 0.7.0-incubating
FLINK_VERSION_HADOOP_2_STABLE: 0.7.0-hadoop2-incubating
FLINK_VERSION_STABLE_SHORT: 0.7.0
FLINK_GITHUB_TAG_STABLE: release-0.7.0

FLINK_VERSION_LATEST: 0.8-incubating-SNAPSHOT
FLINK_VERSION_HADOOP_2_LATEST: 0.8-incubating-hadoop2-SNAPSHOT
FLINK_VERSION_LATEST_SHORT: 0.8
FLINK_GITHUB_TAG_LATEST: master

FLINK_CURRENT_DOCUMENTATION: 0.7-incubating

FLINK_ISSUES_URL: https://issues.apache.org/jira/browse/FLINK
FLINK_GITHUB_URL: https://github.com/apache/incubator-flink
FLINK_GITHUB_CONTRIBUTORS_URL: https://github.com/apache/incubator-flink/graphs/contributors
FLINK_GITHUB_REPO_NAME: incubator-flink

FLINK_DOWNLOAD_URL_SOURCE: http://www.apache.org/dyn/closer.cgi/incubator/flink/flink-0.7.0-incubating/flink-0.7.0-incubating-src.tgz 
FLINK_DOWNLOAD_URL_HADOOP_1_STABLE: http://www.apache.org/dyn/closer.cgi/incubator/flink/flink-0.7.0-incubating/flink-0.7.0-incubating-bin-hadoop1.tgz
FLINK_DOWNLOAD_URL_HADOOP_2_STABLE: http://www.apache.org/dyn/closer.cgi/incubator/flink/flink-0.7.0-incubating/flink-0.7.0-incubating-bin-hadoop2.tgz
FLINK_DOWNLOAD_URL_YARN_STABLE: http://www.apache.org/dyn/closer.cgi/incubator/flink/flink-0.7.0-incubating/flink-0.7.0-incubating-bin-hadoop2-yarn.tgz

FLINK_DOWNLOAD_URL_HADOOP_1_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/flink-0.8-incubating-SNAPSHOT-bin-hadoop1.tgz
FLINK_DOWNLOAD_URL_HADOOP_2_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/flink-0.8-incubating-SNAPSHOT-bin-hadoop2.tgz
FLINK_DOWNLOAD_URL_YARN_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/flink-0.8-incubating-SNAPSHOT-bin-hadoop2-yarn.tgz

#baseurl: /incubator-flink-website

#------------------------------------------------------------------------------
# BUILD CONFIG
#------------------------------------------------------------------------------
# These variables configure the jekyll build (./build_docs.sh). You don't need
# to change anything here.
#------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

  -
    scope:
      path: "docs"
    values:
      layout: docs

highlighter: pygments
markdown: redcarpet
redcarpet:
  # https://help.github.com/articles/github-flavored-markdown
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

exclude: flink-src-repo

# News Posts
paginate: 10
paginate_path: "blog/page:num"
